name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - pycdfpp
  - matplotlib
  - numpy
  - ipympl
  - requests
  - xarray
  - PyYAML
  - pip:
    - speasy
